# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  wp-boilerplate.dev:
    site_hosts:
      - wp-boilerplate.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:roots/bedrock.git
    site_install: true
    site_title: WP Boilerplate
    admin_user: admin
    admin_password: admin
    admin_email: email@drewrawitz.com
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://wp-boilerplate.dev
      wp_siteurl: http://wp-boilerplate.dev/wp
      wp_env: development
      db_name: wp_boilerplate
      db_user: wp_boilerplate
      db_password: wp_boilerplate
